config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  get '/post' => 'posts#tag_search'
  get '/posttop'=>'posts#top'
 
  
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }
  
  

  root 'top#index'
  resources :posts  do
    resources :comments, only: [:create,  :destroy]
    
    resource :favorites, only: [:create, :destroy]

    member do
      get 'search'
      
    end

  end

 


  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: :show 
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
    
   
    

    
   
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    favorite.destroy
     
  end
 
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
    <% if post.favorited_by?(current_user) %>
        <i class="fa fa-heart like-btn"><%=link_to post.favorites.count, post_favorites_path(post.id), method: :delete, remote: true %></i>
    <% else %>
        <i class="fa fa-heart unlike-btn"><%=link_to post.favorites.count, post_favorites_path(post.id), method: :post, remote: true %></i>
    <% end %>
<% else %>
   <i class="fa fa-heart"><%= post.favorites.count %></i>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: "favorites/favorite", locals: {post: @post}) %>");