config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  get '/post' => 'posts#tag_search'
  get '/posttop'=>'posts#top'
 
  
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }
  
  

  root 'top#index'
  resources :posts  do
    resources :comments, only: [:create,  :destroy]
    
    resource :favorites, only: [:create, :destroy]

    member do
      get 'search'
      
    end

  end

 


  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: :show 
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :security

  validates  :title, :text, :security_id, presence: true

  belongs_to :user
  has_many :post_tag_relations,dependent: :destroy
  has_many :tags, through: :post_tag_relations
  has_many :comments, dependent: :destroy

  has_many :favorites
  has_one_attached :image

  

 
 

  

  def self.search(search)
    if search != ""
      Post.where("security_id = #{search}")
    #  else
    #   puts 投稿がありません
    end

    def self.search(search)
      return Post.all unless search
      Post.where(['content LIKE ?', "%#{search}%"])
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 

  def self.posts_serach(search)
    Item.where(['title LIKE ? OR content LIKE ?', "%#{search}%", "%#{search}%"])
  end
 
  def save_posts(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
 
    # Destroy
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end
 
    # Create
    new_tags.each do |new_name|
      item_tag = Tag.find_or_create_by(name:new_name)
      self.tags << item_tag
    end
  end
 


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index 
    @posts = Post.order("created_at DESC")
    if params[:search].present?
      posts = Post.posts_serach(params[:search])
    elsif params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      posts = @tag.posts.order(created_at: :desc)
    else
      posts = Post.all.order(created_at: :desc)
    end
    @tag_lists = Tag.all
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(10)
    
  end

  def new
    @post = PostsTag.new
  end

  def top
    @post = Post.search(params[:search])
    @posts = Post.order("created_at DESC")
    
  end
  



  def create
    @post = PostsTag.new(post_params)
    if @post.valid?
      @post.save
       return redirect_to root_path
    else
      render :new
    end

    tag_list = params[:post][:name].split(nil)
    @item.image.attach(params[:post])
    @item.user_id = current_user.id
    if @item.save
       @item.save_items(tag_list)
      redirect_to posts_path
    else
      flash.now[:alert] = '投稿に失敗しました'
      render 'new'
    end
  end

  def search
    @posts = Post.search(params[:id])
    @post = Post.search(params[:search])
    @posty = Post.where(params[:id]) 
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
   
  end

    
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def tag_search
    @posts = Post.joins(:tags).where(tags:{id: params[:tag_id]})
  end

  def edit
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end
  
  



    





 private
 def post_params
   params.require(:posts_tag).permit(:text, :title, :name, :security_id).merge(user_id: current_user.id)
 end





end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="contents_row">
<span class="name">
      <a href="/users/<%= @post.user.id %>">
        <%= @post.user.nickname %>
      </a>
    </span>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <div class="more">
    
    </div>
     <% end %>
     <div class ="post_all">
        <p class ="post_title"><%= @post.title%></p>
        <p class ="post_text"><%= @post.text %></p>
        <span class="task-time"><%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
     </div>
   
    
     
     <div id="favorites_buttons_<%= @post.id %>">
         <%= render partial: 'favorites/favorite', locals: { post: @post} %>
    </div>
    
  </div>
  <div class="container1">
    <div class="comments">
    
     <div class="row">
        <ul>
            <li class="comment-create">
                <h3 class="text-left title"><i class="fa fa-comments"></i>レビュー</h3>
            </li>
            <li id="comments_area">
                <%= render partial: 'comments/index', locals: { comments: @comments } %>
            </li>
        </ul>
    <hr>
      <% if user_signed_in? %>
          <div class="comment-create">
              <h3 class="text-left">あなたもレビューを投稿しませんか？</h3>
              <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
          </div>
      <% end %>
</div>
      
      
    </div>
  </div>
</div>
<div class="underlay-photo"></div>
<div class="underlay-black"></div>

app/views/posts/index.html.erb
<div class = "body_p">
  <%= link_to posttop_path do%>
      <h3 class="center_i">←一覧へ戻る</h3>
    <% end %>


     <div class ="find_7">
       <h4><i class="fa fa-arrow-down"></i> タグで探す <i class="fa fa-arrow-down"></i></h4>
      </div>
      <li class ="tag_all">
      <ul><% @tag_lists.each do |list|%>
        <%= link_to list.name,post_path(tag_id: list.id), class: 'tag_list'%>
        <% end %>
        </ul>
    </li>
    

    <p class="tag_list_box">
       <% tag.each do |tag|%>
         <%= link_to "#{tag.name}", posts_path(tag), class: 'smaller tag_list'%>
       <% end %>
    </p>
      
        <div class ="find_7">
         <h4><i class="fa fa-arrow-down"></i>  カテゴリーから選ぶ <i class="fa fa-arrow-down"></i></h4>
        </div>
      </div>



      
      <div class="link-7">
        <%= link_to search_post_path(1)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">SQL インジェクション</span>
        <% end %>
        
      </div>
      
      <div class="link-7">
        <%= link_to search_post_path(2)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">OS コマンドインジェクション</span>
        <% end %>
     
      </div>
      
      <div class="link-7">
        <%= link_to search_post_path(3)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">LDAP インジェクション</span>
        <% end %>
        
      </div>

      <div class="link-7">
       <%= link_to search_post_path(4)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">DoS/DDoS</span>
         <% end %>
         
      </div>

      <div class="link-7">
        <%= link_to search_post_path(5)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">クロスサイトスクリプティング</span>
        <% end %>
       
      </div>

      <div class="link-7">
        <%= link_to search_post_path(6)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">ディレクトリ・トラバーサル</span>
        <% end %>
         
      </div>

      <div class="link-7">
       <%= link_to search_post_path(7)  do%>
          <span class="thin"> <i class="fa fa-search-plus"></i> Attack </span><span class="thick">ドライブバイダウンロード</span>
        <% end %>
       
      </div>

      <div class="link-7">
       <%= link_to search_post_path(8)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">ゼロデイ</span>
        <% end %>
        
      </div>

      <div class="link-7">
       <%= link_to search_post_path(9)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">パスワードリスト</span>
        <% end %>
          
      </div>

      <div class="link-7">
        <%= link_to search_post_path(10)  do%>
          <span class="thin"><i class="fa fa-search-plus"></i> Attack </span><span class="thick">ブルートフォースアタック</span>
        <% end %>
        
      </div>

    </div>
 
  </div>
 
</div>

<div class="underlay-photo"></div>
<div class="underlay-black"></div>
 

app/views/posts/new.html.erb
<div class="login-text">
  <h3>NEW POST</h3>
  
  <%= form_with(model: @post, url: posts_path, local: true) do |form| %>
   <%= render 'layouts/error_messages', model: form.object %>

    <div class ="login-username">
    <p>NICKNAME</p>
      <%= current_user.nickname %>
    </div>

    <div class ="login-username">
    <p>TITLE</p>
      <%= form.text_field :title, placeholder: "タイトルを入力" %>
    </div>


   
      <div class="login-username", id='tag-field'>
        <%= form.label :name, "タグ" %>
        <%= form.text_field :name, class:"input-tag" %>
      </div>
      <div id="search-result">
      </div>
    


    <div class ="login-username">
    <p>Type</p>
      <%= form.collection_select(:security_id, Security.all, :id, :name, {include_blank: "--"}, {class:"security-select"}) %>
    </div>

    <div class ="text">
     <p>TEXT</p>
      <%= form.text_area :text, placeholder: "text", rows: "10" %>
    </div>
    
      <%= form.submit "SEND" %>

      
  <% end %>
  
</div>
<div class="underlay-photo"></div>
<div class="underlay-black"></div>

app/views/posts/search.html.erb
<body>
  <%= link_to posts_path do%>
     <h3 class="center_c">←カテゴリー選択へ戻る</h3>
   <% end %>

 
  <div class="container">   
    </h1>
    <% @post.each do |post| %>
      <article class="episode">
        

        <%= link_to user_path(post.user_id) do%>
         <div class="episode__number"><%= post.user.nickname%></div>
        <% end %>
        
        <div class="episode__content">
         <%= link_to  edit_post_path(post.id), method: :get do %>
           <div class="title">"<%= post.title%>"</div>
         <% end %>
       
          <div class="story">
            <%= post.text.truncate(50) %>
          </div>
          <ul class="tag">
          <li class="tag-list">
          
             <% post.tags.each do |tag| %>
               #<%= tag.name %>
             <%end%>
            
          </li>
        </ul>
        </div>
      </article>
    <% end %>
 </div>


 


</body>
<div class="underlay-photo"></div>
<div class="underlay-black"></div>

app/views/posts/tag_search.html.erb
<%= link_to posts_path do%>
     <h3 class="center_c">←カテゴリー選択へ戻る</h3>
<% end %>


<div class="container">

 <h1 class="center"> 

 </h1>

 
  <% @posts.each do |posts| %>
   <article class="episode">
    <li class ="more_list">
      <%= link_to "詳細",  edit_post_path(posts.id), method: :get%> 
   </li>
    

   <%= link_to user_path(posts.user_id) do%>
     <div class="episode__number"><%= posts.user.nickname%></div>
    <% end %>

    <div class="episode__content">  
      <div class="title">"<%= posts.title%>"</div>

      <div class="story">
        <%= posts.text.truncate(50) %>
      </div>
      <ul class="tag">
        <li class="tag-list">
          <% posts.tags.each do |tag| %>
            #<%=tag.name%>
        <%end%>
        </li>
      </ul>
    
  <% end %>
  
</div>

<div class="underlay-photo"></div>
<div class="underlay-black"></div>

app/views/posts/top.html.erb
<%= link_to root_path do%>
      <h3 class="center_i">←トップへ戻る</h3>
    <% end %>


    <div class ="post_title_1">
       <h2>Protect your app in the opinion of someone</h2>
       <p>誰かの意見であなたのアプリを守る</p>

      
      <div class="banner"></div>




<div class="container">

  
<% @posts.each do |post| %>
  <%= link_to user_path(post.user_id) do%>
    <div class="episode__number"><%= post.user.nickname %></div>
    <% end %>

  
    <div class="episode__content">
      <%= link_to edit_post_path(post.id), method: :get do%>
        <div class="title">"<%= post.title%>"
      <% end %>
      </div>


    <div class="story">
      <%= post.text.truncate(50) %>
      </div>

      <ul class="tag">
        <li class="tag-list">
        
          <% post.tags.each do |tag| %>
            #<%= tag.name %>
          <%end%>
          
        </li>
      </ul>

<% end %>
  

 
    
    
    <footer class="footer">
    <div class="container">
          <ul class="nav1">
      <li>
        <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
          <!-- ユーザーがログインしていた時の処理 -->

          
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
        <% else %>
          <!-- ユーザーがログインしていなかった時の処理 -->
         
          <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
        <% end %>
      
      </li>

      <li><%= link_to "検索", posts_path  %></li>

      <li></li>

      <li></li>

    </ul>
    </div>
      
</footer>
<div class="underlay-photo"></div>
<div class="underlay-black"></div>