config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'users/show'
  get '/post' => 'posts#tag_search'
  get '/posttop'=>'posts#top'
 
  
  devise_for :users, controllers: {
   omniauth_callbacks: 'users/omniauth_callbacks',
   registrations: 'users/registrations'
 }
  
  

  root 'top#index'
  resources :posts  do
    resources :comments, only: [:create,  :destroy]
    
    resource :favorites, only: [:create, :destroy]

    member do
      get 'search'
      
    end

  end

 


  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: :show 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post  
  belongs_to :user  

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :security

  validates  :title, :text, :security_id, presence: true

  belongs_to :user
  has_many :post_tag_relations,dependent: :destroy
  has_many :tags, through: :post_tag_relations
  has_many :comments, dependent: :destroy

  has_many :favorites
  has_one_attached :image

  

 
 

  

  def self.search(search)
    if search != ""
      Post.where("security_id = #{search}")
    #  else
    #   puts 投稿がありません
    end

    def self.search(search)
      return Post.all unless search
      Post.where(['content LIKE ?', "%#{search}%"])
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 

  def self.posts_serach(search)
    Item.where(['title LIKE ? OR content LIKE ?', "%#{search}%", "%#{search}%"])
  end
 
  def save_posts(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
 
    # Destroy
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end
 
    # Create
    new_tags.each do |new_name|
      item_tag = Tag.find_or_create_by(name:new_name)
      self.tags << item_tag
    end
  end
 


end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord

  belongs_to :post
  belongs_to :tag
end

app/models/security.rb
class Security < ActiveHash::Base

  self.data = [
    { id: 1, name: 'SQLインジェクション攻撃',                   text: 'SQL injection Attack'},
    { id: 2, name: 'OSコマンドインジェクション攻撃',            text: 'OS command injection Attack' },
    { id: 3, name: 'LDAPインジェクション攻撃',                  text: 'LDAP injection Attack' },
    { id: 4, name: 'DoS/DDoS攻撃',                              text: 'DoS/DDoS Attack' },
    { id: 5, name: 'クロスサイトスクリプティング攻撃',          text: 'XSS Attack' },
    { id: 6, name: 'ディレクトリ・トラバーサル攻撃',            text:'Directory traversal Attack' },
    { id: 7, name: 'ドライブバイダウンロード攻撃',              text: 'Drive by download Attack' },
    { id: 8, name: 'ゼロデイ攻撃',                              text: 'Zero-day Attack' },
    { id: 9, name: 'パスワードリスト攻撃',                      text:'Password list Attack' },
    { id: 10, name: 'ブルートフォースアタック（総当たり攻撃）', text: 'Brute force Attack' },
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :posts, through: :post_tag_relations

  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]



 has_many :posts ,dependent: :destroy
 has_many :sns_credentials
 has_many :comments, dependent: :destroy
 has_many :favorites
 has_many :favorite_posts, through: :favorites, source: :post
 mount_uploader :image, ImageUploader
 

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.save
    render :index
  end

 
  
  

  def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      render :index
  end

  



  private

  

  def comment_params
    params.permit(:post_id).merge(user_id: current_user.id, text: params[:comment][:text])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
    
   
    

    
   
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    favorite.destroy
     
  end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index 
    @posts = Post.order("created_at DESC")
    if params[:search].present?
      posts = Post.posts_serach(params[:search])
    elsif params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      posts = @tag.posts.order(created_at: :desc)
    else
      posts = Post.all.order(created_at: :desc)
    end
    @tag_lists = Tag.all
    @posts = Kaminari.paginate_array(posts).page(params[:page]).per(10)
    
  end

  def new
    @post = PostsTag.new
  end

  def top
    @post = Post.search(params[:search])
    @posts = Post.order("created_at DESC")
    
  end
  



  def create
    @post = PostsTag.new(post_params)
    if @post.valid?
      @post.save
       return redirect_to root_path
    else
      render :new
    end

    tag_list = params[:post][:name].split(nil)
    @item.image.attach(params[:post])
    @item.user_id = current_user.id
    if @item.save
       @item.save_items(tag_list)
      redirect_to posts_path
    else
      flash.now[:alert] = '投稿に失敗しました'
      render 'new'
    end
  end

  def search
    @posts = Post.search(params[:id])
    @post = Post.search(params[:search])
    @posty = Post.where(params[:id]) 
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
   
  end

    
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def tag_search
    @posts = Post.joins(:tags).where(tags:{id: params[:tag_id]})
  end

  def edit
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end
  
  



    





 private
 def post_params
   params.require(:posts_tag).permit(:text, :title, :name, :security_id).merge(user_id: current_user.id)
 end





end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  
  def index
  end

  

private

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: :show


  def show
    @user = User.find(params[:id])
    @post = Post.all.order("created_at DESC")
    @favorite_posts = @user.favorite_posts 
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end


  private

  def set_user
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NETWORK SECURITY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  </head> 

  <body>
   <header>

    <div class="container1">
    <h1 class="logo"><%= link_to "NETWORK SECURITY", root_path  %></h1>
    <ul class="nav1">
      <li>
        <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
          <!-- ユーザーがログインしていた時の処理 -->
         
           <%= link_to current_user.nickname, user_path(current_user.id), method: :get%>

           <%= link_to "新規投稿",  new_post_path %>
         
           
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
        <% else %>
          <!-- ユーザーがログインしていなかった時の処理 -->
         
          <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
        <% end %>
      
      </li>

      <li><%= link_to "検索", posts_path  %></li>

      <li></li>

      <li></li>

    </ul>

  </div>










   </header>
      
     
      <%= yield %>
   
  </body>
</html>

app/views/shared/_ header.html.erb
<header class="header">
  <div class="container1">
    <h1 class="logo"><%= link_to "NETWORK SECURITY", root_path  %></h1>
    <ul class="nav1">
      <li>
        <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
          <!-- ユーザーがログインしていた時の処理 -->

           
             <%= current_user.nickname %>
            
           
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
        <% else %>
          <!-- ユーザーがログインしていなかった時の処理 -->
         
          <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
        <% end %>
      
      </li>

      <li><%= link_to "検索", posts_path  %></li>

      <li></li>

      <li></li>

    </ul>

  </div>
</header>

app/views/shared/_comments.html.erb
<tr id="comment-<%= @comment.id %>">


 <% if @comments %>
    <% @comments.each do |comment| %>
      <p>
        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %></strong> 
        <%= comment.text %>
        <%= comment.created_at.strftime("%Y-%m-%d %H:%M")%>
      </p>
  <% end %>
 <% end %>


   <%# <%= link_to  comment_path(comment),method: :delete, remote: true, data: { confirm: '削除してよろしいですか？' } %> 

</tr>

app/views/shared/_comments_area.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <%= render 'shared/comments' %>
    </table>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>